#include "game/match_rules.h"
#include "server/server_config.h"
#include <filesystem>
#include <fstream>
#include <stdexcept>

int main(){const auto check=[](bool value){if(!value)throw std::runtime_error("headless server assertion failed");};namespace fs=std::filesystem;const auto dir=fs::temp_directory_path()/"bard_battle_headless_rounds";fs::remove_all(dir);fs::create_directories(dir);for(const auto id:{"alpha","beta","gamma"}){std::ofstream(dir/(std::string(id)+".wav"))<<"wav";std::ofstream(dir/(std::string(id)+".cfg"))<<"id="<<id<<"\nfile="<<id<<".wav\nbpm=120\nsubdivision=1\nduration_ms=1000\n";}const auto catalog=SongCatalog::load(dir.string());server::ShuffleBag bag(catalog,12);const net::PlayerId players[]={1,2,3};
// Combined vote: choices can change, a disconnect leaves eligibility, and
// neither section resolves before the complete fifteen-second deadline.
server::RoundConfig combined{true,true,net::GameMode::ffa,3,"",{}};const auto combined_plan=server::prepare_round(combined,bag);check(combined_plan.voting&&combined_plan.candidates.size()==3);game::ModeVote modes;game::SongVote songs;modes.begin(players,100);songs.begin(players,combined_plan.candidates,100);check(modes.submit(1,net::VoteChoice::teams)&&modes.submit(1,net::VoteChoice::ffa));check(modes.submit(2,net::VoteChoice::teams));check(songs.submit(1,0)&&songs.submit(1,1)&&songs.submit(2,1));modes.disconnect(3);songs.disconnect(3);check(!modes.complete(100+game::ModeVote::duration_us-1)&&!songs.complete(100+game::ModeVote::duration_us-1));check(modes.complete(100+game::ModeVote::duration_us)&&songs.complete(100+game::ModeVote::duration_us));check(modes.result()==net::GameMode::ffa);std::mt19937 rng{2};check(songs.result(rng)==combined_plan.candidates[1]);
// Mode-only, song-only, forced no-vote, and automatic no-vote plans.
server::RoundConfig mode_only{true,false,net::GameMode::teams,3,"alpha",{}};auto plan=server::prepare_round(mode_only,bag);check(plan.voting&&plan.candidates.empty()&&plan.selected_song=="alpha");server::RoundConfig song_only{false,true,net::GameMode::teams,2,"",{"gamma","alpha"}};plan=server::prepare_round(song_only,bag);check(plan.voting&&plan.candidates==std::vector<std::string>({"gamma","alpha"}));server::RoundConfig forced{false,false,net::GameMode::teams,3,"beta",{}};plan=server::prepare_round(forced,bag);check(!plan.voting&&plan.selected_song=="beta");forced.force_song.clear();plan=server::prepare_round(forced,bag);check(!plan.voting&&catalog.find(plan.selected_song));
// FFA always allows hits; teams obey friendly fire and team boundaries.
check(game::projectile_can_hit(net::GameMode::ffa,false,1,1));check(!game::projectile_can_hit(net::GameMode::teams,false,1,1));check(game::projectile_can_hit(net::GameMode::teams,true,1,1));check(game::projectile_can_hit(net::GameMode::teams,false,1,2));fs::remove_all(dir);}
