#include "net/protocol.h"

#include <cmath>
#include <iostream>
#include <stdexcept>

int main() {
    const auto require=[](bool condition){if(!condition)throw std::runtime_error("protocol assertion failed");};
    net::Snapshot source{};
    source.server_time_us=123456789;source.server_tick=42;
    source.players.push_back({7,{1.25f,-3.5f},{160.0f,0.0f},99,0xff123456u,"Player"});
    source.players[0].facing_angle=1.25f;source.players[0].respawn_at_us=999;source.players[0].protected_until_us=555;source.players[0].shield_until_us=777;source.players[0].stunned_until_us=888;
    source.players[0].team=2;source.players[0].vote=net::VoteChoice::teams;source.players[0].round_kills=4;source.players[0].round_deaths=2;source.players[0].session_kills=9;source.players[0].session_deaths=6;
    source.players[0].song_vote=1;source.room=net::RoomState::voting;source.mode=net::GameMode::teams;source.vote_deadline_us=555555;source.eligible_voters=3;source.teams_votes=2;source.ffa_votes=1;source.team_count=4;source.friendly_fire=true;source.mode_vote_enabled=true;source.song_vote_enabled=true;source.song_candidates={"a","b","c"};source.song_votes={1,2,0};source.selected_song_id="b";
    source.projectiles.push_back({91,7,{10.0f,20.0f},{480.0f,0.0f},0.5f});source.melee_effects.push_back({92,7,{20.0f,30.0f},24.0f,999999});source.shield_freeze=false;source.shield_melee=net::ShieldMeleeMode::kill;
    const auto bytes=net::make_snapshot(source);net::Reader reader(bytes);
    require(reader.type()==net::MessageType::snapshot);const auto decoded=net::read_snapshot(reader);
    require(decoded.server_time_us==source.server_time_us);require(decoded.server_tick==42);require(decoded.players.size()==1);require(decoded.players[0].id==7);require(std::fabs(decoded.players[0].position.x-1.25f)<0.001f);require(decoded.players[0].name=="Player");require(decoded.players[0].respawn_at_us==999);require(decoded.players[0].shield_until_us==777);require(decoded.players[0].stunned_until_us==888);require(decoded.projectiles.size()==1);require(decoded.projectiles[0].id==91);require(std::fabs(decoded.projectiles[0].velocity.x-480.0f)<0.001f);require(decoded.melee_effects.size()==1);require(decoded.melee_effects[0].owner_id==7);require(!decoded.shield_freeze);require(decoded.shield_melee==net::ShieldMeleeMode::kill);require(reader.finished());
    require(decoded.players[0].team==2);require(decoded.players[0].song_vote==1);require(decoded.players[0].round_kills==4);require(decoded.room==net::RoomState::voting);require(decoded.teams_votes==2);require(decoded.team_count==4);require(decoded.friendly_fire);require(decoded.song_vote_enabled&&decoded.song_candidates[1]=="b"&&decoded.song_votes[1]==2&&decoded.selected_song_id=="b");

    net::SongSchedule schedule{5000000,180000,128.0f,125,2,"main",{125,500,875}};const auto song_bytes=net::make_song_schedule(schedule);net::Reader song_reader(song_bytes);require(song_reader.type()==net::MessageType::song_schedule);const auto decoded_song=net::read_song_schedule(song_reader);require(decoded_song.server_start_us==5000000);require(decoded_song.subdivision==2);require(decoded_song.song_id=="main");require(decoded_song.note_times_ms.size()==3);require(song_reader.finished());
    net::RhythmResult result{};result.grade=net::RhythmGrade::good;result.offset_ms=-52;result.good=1;result.note_index=7;result.combo=3;result.max_combo=5;result.melee_fired=true;const auto result_bytes=net::make_rhythm_result(result);net::Reader result_reader(result_bytes);require(result_reader.type()==net::MessageType::rhythm_result);const auto decoded_result=net::read_rhythm_result(result_reader);require(decoded_result.note_index==7);require(decoded_result.offset_ms==-52);require(decoded_result.combo==3);require(!decoded_result.overstrum);require(decoded_result.melee_fired);require(result_reader.finished());
    const auto shield_hit=net::make_rhythm_hit(3,1000,0,{},net::RhythmAction::shield);net::Reader shield_reader(shield_hit);require(shield_reader.type()==net::MessageType::rhythm_hit);require(shield_reader.u32()==3);require(shield_reader.u64()==1000);require(shield_reader.i16()==0);require(shield_reader.f32()==0.0f);require(shield_reader.f32()==0.0f);require(static_cast<net::RhythmAction>(shield_reader.u8())==net::RhythmAction::shield);require(shield_reader.finished());
    const auto melee_hit=net::make_rhythm_hit(4,2000,0,{1,0},net::RhythmAction::melee);net::Reader melee_reader(melee_hit);require(melee_reader.type()==net::MessageType::rhythm_hit);require(melee_reader.u32()==4);require(melee_reader.u64()==2000);require(melee_reader.i16()==0);require(melee_reader.f32()==1.0f);require(melee_reader.f32()==0.0f);require(static_cast<net::RhythmAction>(melee_reader.u8())==net::RhythmAction::melee);require(melee_reader.finished());
    net::SoundEvent sound{17,net::SoundCue::shot_hit_shield,2,9,{12.0f,-4.0f},123456,true};const auto sound_bytes=net::make_sound_event(sound);net::Reader sound_reader(sound_bytes);require(sound_reader.type()==net::MessageType::sound_event);const auto decoded_sound=net::read_sound_event(sound_reader);require(decoded_sound.id==17);require(decoded_sound.cue==net::SoundCue::shot_hit_shield);require(decoded_sound.source_id==2);require(decoded_sound.target_id==9);require(decoded_sound.participant);require(sound_reader.finished());
    net::Writer bad_sound(net::MessageType::sound_event);bad_sound.u32(1);bad_sound.u8(255);bad_sound.u32(1);bad_sound.u32(2);bad_sound.f32(0);bad_sound.f32(0);bad_sound.u64(1);bad_sound.u8(0);bool bad_sound_rejected=false;try{net::Reader bad_reader(bad_sound.bytes());require(bad_reader.type()==net::MessageType::sound_event);(void)net::read_sound_event(bad_reader);}catch(const std::exception &){bad_sound_rejected=true;}require(bad_sound_rejected);
    net::Writer excessive(net::MessageType::snapshot);excessive.u64(1);excessive.u32(1);excessive.u8(0);excessive.u16(static_cast<std::uint16_t>(net::kMaxProjectiles+1));bool rejected=false;try{net::Reader malformed(excessive.bytes());require(malformed.type()==net::MessageType::snapshot);(void)net::read_snapshot(malformed);}catch(const std::exception &){rejected=true;}require(rejected);
    const auto vote=net::make_vote_request(net::VoteChoice::teams);net::Reader vote_reader(vote);require(vote_reader.type()==net::MessageType::vote_request);require(net::read_vote_request(vote_reader)==net::VoteChoice::teams);require(vote_reader.finished());
    const auto song_vote=net::make_song_vote_request(7);net::Reader song_vote_reader(song_vote);require(song_vote_reader.type()==net::MessageType::song_vote_request);require(net::read_song_vote_request(song_vote_reader)==7);require(song_vote_reader.finished());
    const auto team=net::make_team_request(4);net::Reader team_reader(team);require(team_reader.type()==net::MessageType::team_request);require(net::read_team_request(team_reader)==4);require(team_reader.finished());
    std::cout<<"protocol tests passed\n";
}
