#include "server/server_config.h"
#include "core/error.h"
#include <algorithm>
#include <charconv>
#include <random>
#include <sstream>
#include <unordered_set>

namespace server { namespace {
std::vector<std::string> words(std::string_view text){std::istringstream in{std::string(text)};std::vector<std::string> out;for(std::string s;in>>s;)out.push_back(s);return out;}
std::string value(const std::vector<std::string>&a,std::size_t&i){if(++i>=a.size())fail("Missing value for "+a[i-1]);return a[i];}
bool onoff(const std::string&s,const std::string&flag){if(s=="on")return true;if(s=="off")return false;fail(flag+" must be on or off");}
net::GameMode mode(const std::string&s){if(s=="ffa")return net::GameMode::ffa;if(s=="teams")return net::GameMode::teams;fail("--mode must be ffa or teams");}
std::uint8_t count(const std::string&s){unsigned n=0;auto r=std::from_chars(s.data(),s.data()+s.size(),n);if(r.ec!=std::errc{}||r.ptr!=s.data()+s.size()||n<1||n>8)fail("--song-count must be 1-8");return static_cast<std::uint8_t>(n);}
}
std::string help(){return "Usage: gamer_time_server [--bind IP] [--map PATH] [--songs-dir PATH] [--help]\nThe network port is fixed at 27020. Do not include a port in --bind.\n\nConfigure without restarting:\n  set mode-vote on|off\n  set song-vote on|off\n  set mode ffa|teams\n  set song-count 1-8\n  set force-song ID|off\n  set team-count 2-4\n  set friendly-fire on|off\n\nRound commands:\n  start\n  start [--mode-vote|--no-mode-vote] [--mode ffa|teams]\n        [--song-vote|--no-song-vote] [--song-count 1-8]\n        [--force-song ID|--songs a,b,c]\n\nOther commands: status, songs, stop, kick ID, help, quit\n";}
Config parse_startup(int argc,char**argv){Config c;auto next=[&](int&i,const std::string&a)->std::string{if(i+1>=argc)fail("Missing value for "+a);return argv[++i];};for(int i=1;i<argc;++i){std::string a=argv[i];if(a=="--help")throw std::runtime_error(help());else if(a=="--bind"){c.bind=next(i,a);if(c.bind.empty()||c.bind.find(':')!=std::string::npos)fail("--bind accepts an IP without a port; Gamer Time always uses port 27020");}else if(a=="--map")c.map=next(i,a);else if(a=="--songs-dir")c.songs_dir=next(i,a);else fail("Unknown boot option: "+a+". Configure gameplay with live set commands.\n"+help());}return c;}
RuntimeSettings runtime_settings(const Config&c){return {c.mode_vote,c.song_vote,c.mode,c.song_count,c.force_song,c.team_count,c.friendly_fire};}
RoundConfig defaults_for(const RuntimeSettings&c,std::size_t size){return {c.mode_vote,c.song_vote&&c.force_song.empty()&&size>1,c.mode,c.song_count,c.force_song,{}};}
RoundConfig defaults_for(const Config&c,std::size_t size){return defaults_for(runtime_settings(c),size);}
std::string apply_set_command(std::string_view line,RuntimeSettings&s,const SongCatalog&catalog){auto a=words(line);if(a.size()!=3||a[0]!="set")fail("Usage: set mode-vote on|off | song-vote on|off | mode ffa|teams | song-count 1-8 | force-song ID|off | team-count 2-4 | friendly-fire on|off");const auto&key=a[1],&v=a[2];if(key=="mode-vote")s.mode_vote=onoff(v,key);else if(key=="song-vote")s.song_vote=onoff(v,key);else if(key=="mode")s.mode=mode(v);else if(key=="song-count")s.song_count=count(v);else if(key=="force-song"){if(v=="off")s.force_song.clear();else{if(!catalog.find(v))fail("Unknown song id: "+v);s.force_song=v;}}else if(key=="team-count"){unsigned n=0;auto r=std::from_chars(v.data(),v.data()+v.size(),n);if(r.ec!=std::errc{}||r.ptr!=v.data()+v.size()||n<2||n>4)fail("team-count must be 2-4");s.team_count=static_cast<std::uint8_t>(n);}else if(key=="friendly-fire")s.friendly_fire=onoff(v,key);else fail("Unknown setting: "+key);return key+"="+(key=="mode"?(s.mode==net::GameMode::teams?"teams":"ffa"):key=="force-song"?(s.force_song.empty()?"off":s.force_song):key=="song-count"?std::to_string(s.song_count):key=="team-count"?std::to_string(s.team_count):key=="mode-vote"?(s.mode_vote?"on":"off"):key=="song-vote"?(s.song_vote?"on":"off"):(s.friendly_fire?"on":"off"));}
RoundConfig parse_start_command(std::string_view line,const RoundConfig&base,const SongCatalog&catalog){auto a=words(line);if(a.empty()||a[0]!="start")fail("Expected start command");RoundConfig r=base;bool set_mode=false,set_songs=false,set_count=false,set_force=false;for(std::size_t i=1;i<a.size();++i){if(a[i]=="--mode-vote")r.mode_vote=true;else if(a[i]=="--no-mode-vote")r.mode_vote=false;else if(a[i]=="--song-vote")r.song_vote=true;else if(a[i]=="--no-song-vote")r.song_vote=false;else if(a[i]=="--mode"){r.mode=mode(value(a,i));set_mode=true;}else if(a[i]=="--song-count"){r.song_count=count(value(a,i));set_count=true;}else if(a[i]=="--force-song"){r.force_song=value(a,i);r.song_vote=false;set_force=true;}else if(a[i]=="--songs"){std::stringstream ss(value(a,i));for(std::string id;std::getline(ss,id,',');)r.songs.push_back(id);set_songs=true;}else fail("Unknown start option: "+a[i]);}if(set_force&&(set_songs||set_count))fail("--force-song conflicts with --songs and --song-count");if(set_songs&&!r.song_vote)fail("--songs requires song voting");if(set_mode&&r.mode_vote)fail("--mode requires mode voting to be disabled");if(!r.force_song.empty()&&!catalog.find(r.force_song))fail("Unknown song id: "+r.force_song);if(set_songs){if(r.songs.empty()||r.songs.size()>8)fail("--songs requires 1-8 IDs");std::unordered_set<std::string> seen;for(auto&id:r.songs)if(id.empty()||!catalog.find(id)||!seen.insert(id).second)fail("Unknown or duplicate song id: "+id);}return r;}
ShuffleBag::ShuffleBag(const SongCatalog&c,std::uint32_t seed):random_(seed){for(auto&s:c.songs())all_.push_back(s.id);}
std::vector<std::string> ShuffleBag::draw(std::size_t n){n=std::min(n,all_.size());std::vector<std::string> out;while(out.size()<n){if(bag_.empty()){bag_=all_;std::shuffle(bag_.begin(),bag_.end(),random_);}auto id=bag_.back();bag_.pop_back();if(std::find(out.begin(),out.end(),id)==out.end())out.push_back(std::move(id));}return out;}
PreparedRound prepare_round(const RoundConfig&r,ShuffleBag&bag){PreparedRound out;out.voting=r.mode_vote||r.song_vote;if(r.song_vote)out.candidates=r.songs.empty()?bag.draw(r.song_count):r.songs;else out.selected_song=r.force_song.empty()?bag.draw(1).front():r.force_song;return out;}
}
