#include "render/entity_animations.h"

#include <algorithm>
#include <limits>
#include <stdexcept>

namespace entity_animation {
std::vector<std::string> Catalog::pack(AtlasAsset&atlas,LoadedImage&dst){auto pack_one=[&](std::optional<Strip>&entry){if(!entry)return;auto&s=*entry;try{const LoadedImage src=assets::load_png_rgba(s.image_path.string());const auto need_w=2*s.margin+s.columns*s.source_width+(s.columns-1)*s.spacing;if(src.width<need_w||src.height<s.source_height+2*s.margin)throw std::runtime_error("image geometry is too small");if(!atlas.columns||!atlas.tile_width||atlas.tile_width!=atlas.tile_height||dst.width!=atlas.columns*atlas.tile_width)throw std::runtime_error("invalid destination atlas");const std::uint32_t tile=atlas.tile_width,columns=atlas.columns,span_x=(s.source_width+tile-1)/tile,span_y=(s.source_height+tile-1)/tile;if(!span_x||span_x>columns||!span_y||span_x>std::numeric_limits<std::uint16_t>::max()||span_y>std::numeric_limits<std::uint16_t>::max())throw std::runtime_error("sprite is too large for the atlas");s.atlas_span_x=static_cast<std::uint16_t>(span_x);s.atlas_span_y=static_cast<std::uint16_t>(span_y);const std::uint32_t packed_w=span_x*tile,packed_h=span_y*tile;std::vector<std::uint32_t> indices(s.tile_count);for(std::uint32_t n=0;n<s.tile_count;++n){std::uint32_t first=atlas.logical_tile_count;const std::uint32_t x_cell=first%columns;if(x_cell+span_x>columns)first+=columns-x_cell;const std::uint64_t end=static_cast<std::uint64_t>(first)+(static_cast<std::uint64_t>(span_y)-1)*columns+span_x;if(end>std::numeric_limits<std::uint32_t>::max())throw std::runtime_error("atlas index overflow");atlas.logical_tile_count=static_cast<std::uint32_t>(end);const std::uint32_t rows=(atlas.logical_tile_count+columns-1)/columns;if(rows*tile>dst.height){dst.height=rows*tile;dst.rgba_pixels.resize(static_cast<std::size_t>(dst.width)*dst.height*4,0);}indices[n]=first;const std::uint32_t dx=(first%columns)*tile,dy=(first/columns)*tile,sx=s.margin+n*(s.source_width+s.spacing),sy=s.margin;for(std::uint32_t y=0;y<packed_h;++y)for(std::uint32_t x=0;x<packed_w;++x){const auto source_x=sx+x*s.source_width/packed_w,source_y=sy+y*s.source_height/packed_h;const auto si=(static_cast<std::size_t>(source_y)*src.width+source_x)*4;const auto di=(static_cast<std::size_t>(dy+y)*dst.width+dx+x)*4;std::copy_n(src.rgba_pixels.data()+si,4,dst.rgba_pixels.data()+di);}}for(auto&f:s.frames)f.atlas_index=indices[f.tile_id];}catch(const std::exception&x){warnings_.push_back("could not pack "+s.tsx_path.string()+": "+x.what());entry.reset();}};for(auto&player:players_)for(auto&entry:player)pack_one(entry);for(auto&entry:effects_)pack_one(entry);atlas.rows=dst.height/atlas.tile_height;return warnings_;}
} // namespace entity_animation
