#include "render/entity_animations.h"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <regex>

namespace entity_animation {
namespace {
std::string read(const std::filesystem::path&p){std::ifstream in(p);if(!in)throw std::runtime_error("cannot open file");return {std::istreambuf_iterator<char>(in),{}};}
std::string attr(const std::string&s,const char*n){std::smatch m;const std::regex re(std::string(n)+R"(\s*=\s*["']([^"']*)["'])");return std::regex_search(s,m,re)?m[1].str():std::string{};}
std::uint32_t number(const std::string&s,const char*n){const auto v=attr(s,n);if(v.empty())throw std::runtime_error(std::string("missing ")+n);const auto x=std::stoull(v);if(x>UINT32_MAX)throw std::runtime_error("numeric property overflow");return static_cast<std::uint32_t>(x);}
std::string property(const std::string&s,const std::string&name){const std::regex re(R"(<property\b[^>]*name\s*=\s*["'])"+name+R"(["'][^>]*(?:value\s*=\s*["']([^"']*)["'][^>]*/>|>([^<]*)</property>))");std::smatch m;return std::regex_search(s,m,re)?(m[1].matched?m[1].str():m[2].str()):std::string{};}
float positive_property(const std::string&s,const char*n,float fallback){const auto v=property(s,n);if(v.empty())return fallback;const float x=std::stof(v);if(!std::isfinite(x)||x<=0)throw std::runtime_error(std::string("invalid ")+n);return x;}
std::optional<PlayerAnimation> animation(std::string_view s){static constexpr std::array names{"death","idle","running","attack","melee","shield_break","shield"};for(std::size_t i=0;i<names.size();++i)if(s==names[i])return static_cast<PlayerAnimation>(i);return {};}
std::optional<Role> role(std::string_view s){if(s=="projectile")return Role::projectile;if(s=="melee")return Role::melee;return {};}
}

Catalog Catalog::load(const std::filesystem::path&dir){Catalog out;if(!std::filesystem::exists(dir)){out.warnings_.push_back("entity animation directory is missing: "+dir.string());return out;}std::vector<std::filesystem::path> files;for(const auto&e:std::filesystem::recursive_directory_iterator(dir))if(e.is_regular_file()&&e.path().extension()==".tsx")files.push_back(e.path());std::sort(files.begin(),files.end());for(const auto&path:files)try{const auto xml=read(path);std::optional<Strip>*slot=nullptr;float fallback_w=16,fallback_h=16;const auto player_text=property(xml,"bard.player"),animation_text=property(xml,"bard.animation");if(!player_text.empty()||!animation_text.empty()){const unsigned player=std::stoul(player_text);const auto state=animation(animation_text);if(player<1||player>4||!state)throw std::runtime_error("invalid bard.player or bard.animation");slot=&out.players_[player-1][static_cast<std::size_t>(*state)];}else{const auto effect=role(property(xml,"bard.role"));if(!effect)throw std::runtime_error("missing player animation properties or invalid bard.role");slot=&out.effects_[static_cast<std::size_t>(*effect)];fallback_w=*effect==Role::projectile?18:48;fallback_h=*effect==Role::projectile?6:48;}if(*slot){out.warnings_.push_back("duplicate animation ignored: "+path.string());continue;}Strip s{};s.tsx_path=path;s.source_width=number(xml,"tilewidth");s.source_height=number(xml,"tileheight");s.tile_count=number(xml,"tilecount");s.columns=number(xml,"columns");s.margin=attr(xml,"margin").empty()?0:number(xml,"margin");s.spacing=attr(xml,"spacing").empty()?0:number(xml,"spacing");if(!s.source_width||!s.source_height||!s.tile_count||s.columns!=s.tile_count)throw std::runtime_error("sheet must be one non-empty horizontal row");std::smatch im;if(!std::regex_search(xml,im,std::regex(R"(<image\b[^>]*source\s*=\s*["']([^"']+)["'])")))throw std::runtime_error("missing image source");s.image_path=path.parent_path()/im[1].str();s.world_size={positive_property(xml,"bard.world_width",fallback_w),positive_property(xml,"bard.world_height",fallback_h)};const std::regex fr(R"(<frame\b[^>]*tileid\s*=\s*["']([0-9]+)["'][^>]*duration\s*=\s*["']([0-9]+)["'][^>]*/>)");for(auto i=std::sregex_iterator(xml.begin(),xml.end(),fr);i!=std::sregex_iterator();++i){Frame f{static_cast<std::uint32_t>(std::stoul((*i)[1].str())),static_cast<std::uint32_t>(std::stoul((*i)[2].str())),0};if(f.tile_id>=s.tile_count||!f.duration_ms)throw std::runtime_error("invalid animation frame");s.frames.push_back(f);}if(s.frames.empty())throw std::runtime_error("missing tile animation");*slot=std::move(s);}catch(const std::exception&x){out.warnings_.push_back("invalid entity TSX "+path.string()+": "+x.what());}return out;}

const Strip*Catalog::find_player(std::uint8_t player,PlayerAnimation state)const{if(player<1||player>4)player=1;const auto&exact=players_[player-1][static_cast<std::size_t>(state)];if(exact)return &*exact;const auto&idle=players_[player-1][static_cast<std::size_t>(PlayerAnimation::idle)];if(idle)return &*idle;const auto&default_idle=players_[0][static_cast<std::size_t>(PlayerAnimation::idle)];return default_idle?&*default_idle:nullptr;}
const Strip*Catalog::find(Role r)const{const auto&v=effects_[static_cast<std::size_t>(r)];return v?&*v:nullptr;}
std::uint64_t duration_us(const Strip&s){std::uint64_t total=0;for(const auto&f:s.frames)total+=f.duration_ms;return total*1000;}
std::uint32_t frame_index(const Strip&s,std::uint64_t us,bool loop){if(s.frames.empty())return 0;const auto total=duration_us(s)/1000;if(!total)return 0;std::uint64_t ms=us/1000;if(loop)ms%=total;else if(ms>=total)return static_cast<std::uint32_t>(s.frames.size()-1);std::uint64_t end=0;for(std::uint32_t i=0;i<s.frames.size();++i){end+=s.frames[i].duration_ms;if(ms<end)return i;}return static_cast<std::uint32_t>(s.frames.size()-1);}
std::uint8_t player_folder(std::uint32_t player_id,std::uint8_t team,bool teams){if(teams&&team>=1&&team<=4)return team;if(player_id==0)return 1;return static_cast<std::uint8_t>((player_id-1)%4+1);}
} // namespace entity_animation
