#include "game/match_rules.h"
#include "ui/ui_model.h"
#include <stdexcept>
#include <iostream>

int main(){auto check=[](bool v){if(!v)throw std::runtime_error("match/ui assertion failed");};
 game::ModeVote vote;const net::PlayerId ids[]={1,2,3};vote.begin(ids,100);check(!vote.complete(101));check(vote.submit(1,net::VoteChoice::teams));check(vote.submit(1,net::VoteChoice::ffa));check(vote.choice(1)==net::VoteChoice::ffa);check(vote.submit(2,net::VoteChoice::ffa));vote.disconnect(3);check(vote.eligible_count()==2);check(!vote.complete(102));check(vote.result()==net::GameMode::ffa);
 vote.begin(ids,100);check(vote.complete(100+game::ModeVote::duration_us));check(vote.result()==net::GameMode::ffa);check(!vote.submit(9,net::VoteChoice::teams));
 game::ModeVote teams;teams.begin(ids,0);check(teams.submit(1,net::VoteChoice::teams));check(teams.submit(2,net::VoteChoice::teams));check(teams.submit(3,net::VoteChoice::ffa));check(teams.result()==net::GameMode::teams);teams.submit(2,net::VoteChoice::ffa);check(teams.result()==net::GameMode::ffa);
 const std::string candidates[]={"a","b","c"};game::SongVote songs;songs.begin(ids,candidates,1000);check(!songs.complete(1000+game::ModeVote::duration_us-1));check(songs.submit(1,0));check(songs.submit(1,2));check(songs.choice(1)==2);check(songs.submit(2,2));check(songs.totals()==std::vector<std::uint8_t>({0,0,2}));check(!songs.submit(9,0));check(!songs.submit(2,3));songs.disconnect(2);check(songs.totals()==std::vector<std::uint8_t>({0,0,1}));check(songs.complete(1000+game::ModeVote::duration_us));std::mt19937 fixed{7};check(songs.result(fixed)=="c");
 game::SongVote zero;zero.begin(ids,candidates,0);std::mt19937 tie_random{9};const auto zero_result=zero.result(tie_random);check(zero_result=="a"||zero_result=="b"||zero_result=="c");
 check(game::projectile_can_hit(net::GameMode::ffa,false,1,1));check(!game::projectile_can_hit(net::GameMode::teams,false,1,1));check(game::projectile_can_hit(net::GameMode::teams,true,1,1));check(game::projectile_can_hit(net::GameMode::teams,false,1,2));check(game::kill_is_awarded(net::GameMode::ffa,1,1));check(!game::kill_is_awarded(net::GameMode::teams,1,1));
 check(!game::projectile_can_hit(net::GameMode::teams,false,1,1));check(game::projectile_can_hit(net::GameMode::teams,true,1,1));check(!game::kill_is_awarded(net::GameMode::teams,2,2));check(game::kill_is_awarded(net::GameMode::teams,1,2));
 std::string host;std::uint16_t port=0;check(ui::valid_player_name("Player One"));check(!ui::valid_player_name("   "));check(ui::parse_endpoint("localhost",host,port)&&port==net::kServerPort);check(ui::parse_endpoint("10.0.0.2",host,port)&&host=="10.0.0.2"&&port==net::kServerPort);check(!ui::parse_endpoint("10.0.0.2:27020",host,port));check(!ui::parse_endpoint("host:3000",host,port));
 std::vector<net::PlayerState> players(64);for(std::size_t i=0;i<players.size();++i){players[i].id=static_cast<net::PlayerId>(i+1);players[i].name="Player"+std::to_string(i);players[i].round_kills=static_cast<std::uint32_t>(i%5);players[i].round_deaths=static_cast<std::uint32_t>(i%3);players[i].team=static_cast<net::TeamId>(i%4+1);}auto sorted=ui::sort_ffa(players);check(sorted.front().round_kills==4);auto layout=ui::scoreboard_layout(64,1280,720);check(layout.columns==2&&layout.rows_per_column>=32&&layout.font_scale>0);auto groups=ui::sort_teams(players,4);check(groups.size()==4);check(ui::truncate_ellipsis("abcdefgh",6)=="abc...");
 std::cout<<"match/ui tests passed\n";}
