#include "server/server_config.h"
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <unordered_set>

int main(){const auto check=[](bool ok){if(!ok)throw std::runtime_error("server config assertion failed");};const auto rejects=[&](auto action){try{action();return false;}catch(...){return true;}};namespace fs=std::filesystem;const auto dir=fs::temp_directory_path()/"gamer_time_catalog_test";fs::remove_all(dir);fs::create_directories(dir);for(const auto id:{"a","b","c","d"}){std::ofstream(dir/(std::string(id)+".wav"))<<"wav";std::ofstream(dir/(std::string(id)+".cfg"))<<"id="<<id<<"\nfile="<<id<<".wav\nbpm=120\nfirst_beat_ms=0\nsubdivision=1\nduration_ms=1000\n";}const auto catalog=SongCatalog::load(dir.string());check(catalog.songs().size()==4&&catalog.find("a")&&fs::path(catalog.find("a")->file).is_absolute());
server::Config startup;auto settings=server::runtime_settings(startup);check(settings.mode_vote&&settings.song_vote&&settings.mode==net::GameMode::ffa&&settings.song_count==3&&settings.team_count==2&&!settings.friendly_fire);
{char a0[]="server",a1[]="--bind",a2[]="127.0.0.1",a3[]="--map",a4[]="map.tmx",a5[]="--songs-dir",a6[]="songs";char*argv[]={a0,a1,a2,a3,a4,a5,a6};const auto boot=server::parse_startup(7,argv);check(boot.bind==a2&&boot.map==a4&&boot.songs_dir==a6);}check(rejects([&]{char a0[]="server",a1[]="--bind",a2[]="127.0.0.1:27020";char*argv[]={a0,a1,a2};server::parse_startup(3,argv);}));check(rejects([&]{char a0[]="server",a1[]="--mode-vote",a2[]="off";char*argv[]={a0,a1,a2};server::parse_startup(3,argv);}));check(rejects([&]{char a0[]="server",a1[]="--friendly-fire",a2[]="on";char*argv[]={a0,a1,a2};server::parse_startup(3,argv);}));
check(server::apply_set_command("set mode-vote off",settings,catalog)=="mode-vote=off"&&!settings.mode_vote);check(server::apply_set_command("set mode-vote on",settings,catalog)=="mode-vote=on"&&settings.mode_vote);check(server::apply_set_command("set song-vote off",settings,catalog)=="song-vote=off"&&!settings.song_vote);check(server::apply_set_command("set song-vote on",settings,catalog)=="song-vote=on"&&settings.song_vote);check(server::apply_set_command("set mode teams",settings,catalog)=="mode=teams"&&settings.mode==net::GameMode::teams);check(server::apply_set_command("set mode ffa",settings,catalog)=="mode=ffa"&&settings.mode==net::GameMode::ffa);check(server::apply_set_command("set song-count 4",settings,catalog)=="song-count=4"&&settings.song_count==4);check(server::apply_set_command("set force-song b",settings,catalog)=="force-song=b"&&settings.force_song=="b");check(server::apply_set_command("set force-song off",settings,catalog)=="force-song=off"&&settings.force_song.empty());check(server::apply_set_command("set team-count 4",settings,catalog)=="team-count=4"&&settings.team_count==4);check(server::apply_set_command("set friendly-fire on",settings,catalog)=="friendly-fire=on"&&settings.friendly_fire);check(server::apply_set_command("set friendly-fire off",settings,catalog)=="friendly-fire=off"&&!settings.friendly_fire);
check(rejects([&]{server::apply_set_command("set mode-vote maybe",settings,catalog);}));check(rejects([&]{server::apply_set_command("set song-count 0",settings,catalog);}));check(rejects([&]{server::apply_set_command("set song-count 9",settings,catalog);}));check(rejects([&]{server::apply_set_command("set team-count 1",settings,catalog);}));check(rejects([&]{server::apply_set_command("set force-song missing",settings,catalog);}));check(rejects([&]{server::apply_set_command("set mystery on",settings,catalog);}));check(rejects([&]{server::apply_set_command("set mode",settings,catalog);}));
const auto round=server::defaults_for(settings,catalog.songs().size());check(round.mode_vote&&round.song_vote&&round.song_count==4);const auto explicit_round=server::parse_start_command("start --mode-vote --song-vote --songs d,b,a",round,catalog);check(explicit_round.songs==std::vector<std::string>({"d","b","a"}));const auto forced=server::parse_start_command("start --no-mode-vote --mode teams --no-song-vote --force-song a",round,catalog);check(!forced.mode_vote&&!forced.song_vote&&forced.mode==net::GameMode::teams&&forced.force_song=="a");check(rejects([&]{server::parse_start_command("start --force-song a --song-count 2",round,catalog);}));check(rejects([&]{server::parse_start_command("start --no-song-vote --songs a,b",round,catalog);}));check(rejects([&]{server::parse_start_command("start --mode-vote --mode teams",round,catalog);}));check(rejects([&]{server::parse_start_command("start --song-vote --songs a,a",round,catalog);}));
server::ShuffleBag bag(catalog,1);const auto first=bag.draw(3),second=bag.draw(3);check(first.size()==3&&std::unordered_set<std::string>(first.begin(),first.end()).size()==3);check(second.size()==3&&std::unordered_set<std::string>(second.begin(),second.end()).size()==3);std::unordered_set<std::string> first_four(first.begin(),first.end());first_four.insert(second.front());check(first_four.size()==4);
server::ShuffleBag rounds(catalog,4);server::RoundConfig combined{true,true,net::GameMode::ffa,3,"",{}};auto prepared=server::prepare_round(combined,rounds);check(prepared.voting&&prepared.candidates.size()==3&&prepared.selected_song.empty());server::RoundConfig song_only{false,true,net::GameMode::teams,2,"",{"d","a"}};prepared=server::prepare_round(song_only,rounds);check(prepared.voting&&prepared.candidates==std::vector<std::string>({"d","a"}));server::RoundConfig mode_only{true,false,net::GameMode::ffa,3,"b",{}};prepared=server::prepare_round(mode_only,rounds);check(prepared.voting&&prepared.candidates.empty()&&prepared.selected_song=="b");server::RoundConfig no_vote{false,false,net::GameMode::teams,3,"c",{}};prepared=server::prepare_round(no_vote,rounds);check(!prepared.voting&&prepared.selected_song=="c");no_vote.force_song.clear();prepared=server::prepare_round(no_vote,rounds);check(!prepared.voting&&!prepared.selected_song.empty()&&catalog.find(prepared.selected_song));fs::remove_all(dir);}
